{% set name = "cca-spec-babel" %}
{% set version = "0.8.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/{{ name }}

requirements:
  build:
    - python >=2.7.13,<3
    - cca-babel <2
    - libxml2
    - libiconv [osx]

  run:
    - python >=2.7.13,<3
    - cca-babel <2
    - libxml2
    - libiconv [osx]

build:
  number: 0
